const incentiveData = [
    {
        "Id":  "1",
        "Quarter":  "Q1",
        "Product4Incentive":  "132,896 ",
        "IncentiveAmountSalesResult":  "664,482",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "199,345 ",
        "TotalIncentiveAmount":  "704,035",
        "Position":  "Medical Representative",
        "Product3Incentive":  "166,121 ",
        "IncentiveAmountTCFA":  "39,553",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Abasheva Anna",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "166,121 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "2",
        "Quarter":  "Q1",
        "Product4Incentive":  "15,821 ",
        "IncentiveAmountSalesResult":  "316,420",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "158,210 ",
        "TotalIncentiveAmount":  "395,525",
        "Position":  "Medical Representative",
        "Product3Incentive":  "31,642 ",
        "IncentiveAmountTCFA":  "79,105",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Aitbenbetova Dinara",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "110,747 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "3",
        "Quarter":  "Q1",
        "Product4Incentive":  "14,239 ",
        "IncentiveAmountSalesResult":  "284,778",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "142,389 ",
        "TotalIncentiveAmount":  "363,883",
        "Position":  "Medical Representative",
        "Product3Incentive":  "28,478 ",
        "IncentiveAmountTCFA":  "79,105",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Akhmadiyeva Gulzhan",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "99,672 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "4",
        "Quarter":  "Q1",
        "Product4Incentive":  "12,973 ",
        "IncentiveAmountSalesResult":  "259,464",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "116,759 ",
        "TotalIncentiveAmount":  "338,569",
        "Position":  "Medical Representative",
        "Product3Incentive":  "64,866 ",
        "IncentiveAmountTCFA":  "79,105",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Akhmetova (Imanzhanova) Sholpan",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "64,866 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "5",
        "Quarter":  "Q1",
        "Product4Incentive":  "39,553 ",
        "IncentiveAmountSalesResult":  "791,050",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "395,525 ",
        "TotalIncentiveAmount":  "870,155",
        "Position":  "Medical Representative",
        "Product3Incentive":  "79,105 ",
        "IncentiveAmountTCFA":  "79,105",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Aliyev Askar",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "276,868 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "6",
        "Quarter":  "Q1",
        "Product4Incentive":  "158,210 ",
        "IncentiveAmountSalesResult":  "791,050",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "237,315 ",
        "TotalIncentiveAmount":  "870,155",
        "Position":  "Medical Representative",
        "Product3Incentive":  "197,763 ",
        "IncentiveAmountTCFA":  "79,105",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Altynbassova Shynar",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "197,763 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "7",
        "Quarter":  "Q1",
        "Product4Incentive":  "50,627 ",
        "IncentiveAmountSalesResult":  "506,272",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "227,822 ",
        "TotalIncentiveAmount":  "585,377",
        "Position":  "Pharm Representative",
        "Product3Incentive":  "75,941 ",
        "IncentiveAmountTCFA":  "79,105",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Alzhanova Zhuldyz",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "151,882 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "8",
        "Quarter":  "Q1",
        "Product4Incentive":  "94,926 ",
        "IncentiveAmountSalesResult":  "316,420",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "31,642 ",
        "TotalIncentiveAmount":  "395,525",
        "Position":  "Medical Representative",
        "Product3Incentive":  "94,926 ",
        "IncentiveAmountTCFA":  "79,105",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Arestova Yelena",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "94,926 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "9",
        "Quarter":  "Q1",
        "Product4Incentive":  "158,210 ",
        "IncentiveAmountSalesResult":  "791,050",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "237,315 ",
        "TotalIncentiveAmount":  "830,603",
        "Position":  "Medical Representative",
        "Product3Incentive":  "197,763 ",
        "IncentiveAmountTCFA":  "39,553",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Auyelbekova Syndykul",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "197,763 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "10",
        "Quarter":  "Q1",
        "Product4Incentive":  "113,911 ",
        "IncentiveAmountSalesResult":  "379,704",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "37,970 ",
        "TotalIncentiveAmount":  "458,809",
        "Position":  "Medical Representative",
        "Product3Incentive":  "113,911 ",
        "IncentiveAmountTCFA":  "79,105",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Aybolova Zhazira",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "113,911 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "11",
        "Quarter":  "Q1",
        "Product4Incentive":  "158,210 ",
        "IncentiveAmountSalesResult":  "791,050",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "237,315 ",
        "TotalIncentiveAmount":  "870,155",
        "Position":  "Medical Representative",
        "Product3Incentive":  "197,763 ",
        "IncentiveAmountTCFA":  "79,105",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Baimysheva Mariya",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "197,763 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "12",
        "Quarter":  "Q1",
        "Product4Incentive":  "32,433 ",
        "IncentiveAmountSalesResult":  "648,661",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "291,897 ",
        "TotalIncentiveAmount":  "727,766",
        "Position":  "Medical Representative",
        "Product3Incentive":  "162,165 ",
        "IncentiveAmountTCFA":  "79,105",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Bakisheva Aliya",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "162,165 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "13",
        "Quarter":  "Q1",
        "Product4Incentive":  "91,129 ",
        "IncentiveAmountSalesResult":  "303,763",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "30,376 ",
        "TotalIncentiveAmount":  "382,868",
        "Position":  "Medical Representative",
        "Product3Incentive":  "91,129 ",
        "IncentiveAmountTCFA":  "79,105",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Balanesku Irina",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "91,129 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "14",
        "Quarter":  "Q1",
        "Product4Incentive":  "12,973 ",
        "IncentiveAmountSalesResult":  "259,464",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "116,759 ",
        "TotalIncentiveAmount":  "338,569",
        "Position":  "Medical Representative",
        "Product3Incentive":  "64,866 ",
        "IncentiveAmountTCFA":  "79,105",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Balmagambetova Zamza",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "64,866 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "15",
        "Quarter":  "Q1",
        "Product4Incentive":  "23,732 ",
        "IncentiveAmountSalesResult":  "474,630",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "237,315 ",
        "TotalIncentiveAmount":  "514,183",
        "Position":  "Medical Representative",
        "Product3Incentive":  "47,463 ",
        "IncentiveAmountTCFA":  "39,553",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Bayzakova Gulzhan",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "166,121 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "16",
        "Quarter":  "Q1",
        "Product4Incentive":  "26,896 ",
        "IncentiveAmountSalesResult":  "537,914",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "268,957 ",
        "TotalIncentiveAmount":  "617,019",
        "Position":  "Medical Representative",
        "Product3Incentive":  "53,791 ",
        "IncentiveAmountTCFA":  "79,105",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Bekbauova Saltanat",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "188,270 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "17",
        "Quarter":  "Q1",
        "Product4Incentive":  "0 ",
        "IncentiveAmountSalesResult":  "0",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "0.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "0 ",
        "TotalIncentiveAmount":  "0",
        "Position":  "Medical Representative",
        "Product3Incentive":  "0 ",
        "IncentiveAmountTCFA":  "0",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Boyarova Alfiya",
        "TargetIncentiveTCFA":  "0",
        "Product2Incentive":  "0 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "18",
        "Quarter":  "Q1",
        "Product4Incentive":  "0 ",
        "IncentiveAmountSalesResult":  "0",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "0.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "0 ",
        "TotalIncentiveAmount":  "0",
        "Position":  "Medical Representative",
        "Product3Incentive":  "0 ",
        "IncentiveAmountTCFA":  "0",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Brialinova Inkar",
        "TargetIncentiveTCFA":  "0",
        "Product2Incentive":  "0 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "19",
        "Quarter":  "Q1",
        "Product4Incentive":  "15,821 ",
        "IncentiveAmountSalesResult":  "316,420",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "158,210 ",
        "TotalIncentiveAmount":  "395,525",
        "Position":  "Medical Representative",
        "Product3Incentive":  "31,642 ",
        "IncentiveAmountTCFA":  "79,105",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Donayeva Nazira",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "110,747 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "20",
        "Quarter":  "Q1",
        "Product4Incentive":  "50,627 ",
        "IncentiveAmountSalesResult":  "506,272",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "227,822 ",
        "TotalIncentiveAmount":  "585,377",
        "Position":  "Pharm Representative",
        "Product3Incentive":  "75,941 ",
        "IncentiveAmountTCFA":  "79,105",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Dratkov Grigoriy",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "151,882 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "21",
        "Quarter":  "Q1",
        "Product4Incentive":  "23,732 ",
        "IncentiveAmountSalesResult":  "474,630",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "237,315 ",
        "TotalIncentiveAmount":  "553,735",
        "Position":  "Medical Representative",
        "Product3Incentive":  "47,463 ",
        "IncentiveAmountTCFA":  "79,105",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Feist Yekaterina",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "166,121 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "22",
        "Quarter":  "Q1",
        "Product4Incentive":  "43,560 ",
        "IncentiveAmountSalesResult":  "871,200",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "580,800.00",
        "TargetIncentiveBase":  "726,000.00",
        "TargetIncentiveForQuarter":  "726,000.00 ",
        "Product1Incentive":  "435,600 ",
        "TotalIncentiveAmount":  "1,016,400",
        "Position":  "Regional Manager",
        "Product3Incentive":  "174,240 ",
        "IncentiveAmountTCFA":  "72,600",
        "TargetIncentiveCoaching":  "72,600",
        "IncentiveAmountCoaching":  "72,600",
        "Name":  "Galiyeva Saule",
        "TargetIncentiveTCFA":  "72,600",
        "Product2Incentive":  "217,800 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "23",
        "Quarter":  "Q1",
        "Product4Incentive":  "17,403 ",
        "IncentiveAmountSalesResult":  "348,062",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "174,031 ",
        "TotalIncentiveAmount":  "387,615",
        "Position":  "Medical Representative",
        "Product3Incentive":  "34,806 ",
        "IncentiveAmountTCFA":  "39,553",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Gulyakova Olga",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "121,822 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "24",
        "Quarter":  "Q1",
        "Product4Incentive":  "15,821 ",
        "IncentiveAmountSalesResult":  "316,420",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "158,210 ",
        "TotalIncentiveAmount":  "395,525",
        "Position":  "Medical Representative",
        "Product3Incentive":  "31,642 ",
        "IncentiveAmountTCFA":  "79,105",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Inkarbekova Nurbibi",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "110,747 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "25",
        "Quarter":  "Q1",
        "Product4Incentive":  "69,612 ",
        "IncentiveAmountSalesResult":  "348,062",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "104,419 ",
        "TotalIncentiveAmount":  "387,615",
        "Position":  "Medical Representative",
        "Product3Incentive":  "87,016 ",
        "IncentiveAmountTCFA":  "39,553",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Issakhanova Assem",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "87,016 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "26",
        "Quarter":  "Q1",
        "Product4Incentive":  "15,821 ",
        "IncentiveAmountSalesResult":  "316,420",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "158,210 ",
        "TotalIncentiveAmount":  "395,525",
        "Position":  "Medical Representative",
        "Product3Incentive":  "31,642 ",
        "IncentiveAmountTCFA":  "79,105",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Issakova Dina",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "110,747 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "27",
        "Quarter":  "Q1",
        "Product4Incentive":  "50,627 ",
        "IncentiveAmountSalesResult":  "506,272",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "227,822 ",
        "TotalIncentiveAmount":  "585,377",
        "Position":  "Pharm Representative",
        "Product3Incentive":  "75,941 ",
        "IncentiveAmountTCFA":  "79,105",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Itakhunov Rassul",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "151,882 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "28",
        "Quarter":  "Q1",
        "Product4Incentive":  "113,911 ",
        "IncentiveAmountSalesResult":  "379,704",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "37,970 ",
        "TotalIncentiveAmount":  "419,257",
        "Position":  "Medical Representative",
        "Product3Incentive":  "113,911 ",
        "IncentiveAmountTCFA":  "39,553",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Kadyrova Azaliya",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "113,911 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "29",
        "Quarter":  "Q1",
        "Product4Incentive":  "69,612 ",
        "IncentiveAmountSalesResult":  "348,062",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "104,419 ",
        "TotalIncentiveAmount":  "427,167",
        "Position":  "Medical Representative",
        "Product3Incentive":  "87,016 ",
        "IncentiveAmountTCFA":  "79,105",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Kalistratova Alexandra",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "87,016 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "30",
        "Quarter":  "Q1",
        "Product4Incentive":  "26,896 ",
        "IncentiveAmountSalesResult":  "537,914",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "268,957 ",
        "TotalIncentiveAmount":  "577,467",
        "Position":  "Medical Representative",
        "Product3Incentive":  "53,791 ",
        "IncentiveAmountTCFA":  "39,553",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Kassenova Gulshat",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "188,270 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "31",
        "Quarter":  "Q1",
        "Product4Incentive":  "39,553 ",
        "IncentiveAmountSalesResult":  "791,050",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "395,525 ",
        "TotalIncentiveAmount":  "870,155",
        "Position":  "Medical Representative",
        "Product3Incentive":  "79,105 ",
        "IncentiveAmountTCFA":  "79,105",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Khalikova Nuriya",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "276,868 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "32",
        "Quarter":  "Q1",
        "Product4Incentive":  "94,926 ",
        "IncentiveAmountSalesResult":  "316,420",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "31,642 ",
        "TotalIncentiveAmount":  "395,525",
        "Position":  "Medical Representative",
        "Product3Incentive":  "94,926 ",
        "IncentiveAmountTCFA":  "79,105",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Kuchshanova Akmaral",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "94,926 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "33",
        "Quarter":  "Q1",
        "Product4Incentive":  "132,896 ",
        "IncentiveAmountSalesResult":  "442,988",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "44,299 ",
        "TotalIncentiveAmount":  "522,093",
        "Position":  "Medical Representative",
        "Product3Incentive":  "132,896 ",
        "IncentiveAmountTCFA":  "79,105",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Kussainova Dilara",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "132,896 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "34",
        "Quarter":  "Q1",
        "Product4Incentive":  "0 ",
        "IncentiveAmountSalesResult":  "0",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "0.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "0 ",
        "TotalIncentiveAmount":  "0",
        "Position":  "Medical Representative",
        "Product3Incentive":  "0 ",
        "IncentiveAmountTCFA":  "0",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Kutdussova Liliya",
        "TargetIncentiveTCFA":  "0",
        "Product2Incentive":  "0 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "35",
        "Quarter":  "Q1",
        "Product4Incentive":  "94,926 ",
        "IncentiveAmountSalesResult":  "316,420",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "31,642 ",
        "TotalIncentiveAmount":  "355,973",
        "Position":  "Medical Representative",
        "Product3Incentive":  "94,926 ",
        "IncentiveAmountTCFA":  "39,553",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Kutlymuratov Assylatdin",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "94,926 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "36",
        "Quarter":  "Q1",
        "Product4Incentive":  "31,944 ",
        "IncentiveAmountSalesResult":  "638,880",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "580,800.00",
        "TargetIncentiveBase":  "726,000.00",
        "TargetIncentiveForQuarter":  "726,000.00 ",
        "Product1Incentive":  "319,440 ",
        "TotalIncentiveAmount":  "747,780",
        "Position":  "Regional Manager",
        "Product3Incentive":  "127,776 ",
        "IncentiveAmountTCFA":  "36,300",
        "TargetIncentiveCoaching":  "72,600",
        "IncentiveAmountCoaching":  "72,600",
        "Name":  "Kuxa Anna",
        "TargetIncentiveTCFA":  "72,600",
        "Product2Incentive":  "159,720 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "37",
        "Quarter":  "Q1",
        "Product4Incentive":  "72,600 ",
        "IncentiveAmountSalesResult":  "1,452,000",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "580,800.00",
        "TargetIncentiveBase":  "726,000.00",
        "TargetIncentiveForQuarter":  "726,000.00 ",
        "Product1Incentive":  "726,000 ",
        "TotalIncentiveAmount":  "1,597,200",
        "Position":  "Regional Manager",
        "Product3Incentive":  "290,400 ",
        "IncentiveAmountTCFA":  "72,600",
        "TargetIncentiveCoaching":  "72,600",
        "IncentiveAmountCoaching":  "72,600",
        "Name":  "Kuzikeyeva Dinara",
        "TargetIncentiveTCFA":  "72,600",
        "Product2Incentive":  "363,000 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "38",
        "Quarter":  "Q1",
        "Product4Incentive":  "91,129 ",
        "IncentiveAmountSalesResult":  "303,763",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "30,376 ",
        "TotalIncentiveAmount":  "382,868",
        "Position":  "Medical Representative",
        "Product3Incentive":  "91,129 ",
        "IncentiveAmountTCFA":  "79,105",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Kuznetsova Natalya",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "91,129 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "39",
        "Quarter":  "Q1",
        "Product4Incentive":  "53,791 ",
        "IncentiveAmountSalesResult":  "537,914",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "242,061 ",
        "TotalIncentiveAmount":  "617,019",
        "Position":  "Pharm Representative",
        "Product3Incentive":  "80,687 ",
        "IncentiveAmountTCFA":  "79,105",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Litvinenko Tatyana",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "161,374 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "40",
        "Quarter":  "Q1",
        "Product4Incentive":  "29,040 ",
        "IncentiveAmountSalesResult":  "580,800",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "580,800.00",
        "TargetIncentiveBase":  "726,000.00",
        "TargetIncentiveForQuarter":  "726,000.00 ",
        "Product1Incentive":  "290,400 ",
        "TotalIncentiveAmount":  "726,000",
        "Position":  "Regional Manager",
        "Product3Incentive":  "116,160 ",
        "IncentiveAmountTCFA":  "72,600",
        "TargetIncentiveCoaching":  "72,600",
        "IncentiveAmountCoaching":  "72,600",
        "Name":  "Maisutova Almagul",
        "TargetIncentiveTCFA":  "72,600",
        "Product2Incentive":  "145,200 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "41",
        "Quarter":  "Q1",
        "Product4Incentive":  "0 ",
        "IncentiveAmountSalesResult":  "0",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "0.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "0 ",
        "TotalIncentiveAmount":  "0",
        "Position":  "Medical Representative",
        "Product3Incentive":  "0 ",
        "IncentiveAmountTCFA":  "0",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Mamedova Zarina",
        "TargetIncentiveTCFA":  "0",
        "Product2Incentive":  "0 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "42",
        "Quarter":  "Q1",
        "Product4Incentive":  "37,970 ",
        "IncentiveAmountSalesResult":  "759,408",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "379,704 ",
        "TotalIncentiveAmount":  "838,513",
        "Position":  "Medical Representative",
        "Product3Incentive":  "75,941 ",
        "IncentiveAmountTCFA":  "79,105",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Mamutova Aliya",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "265,793 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "43",
        "Quarter":  "Q1",
        "Product4Incentive":  "94,926 ",
        "IncentiveAmountSalesResult":  "316,420",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "31,642 ",
        "TotalIncentiveAmount":  "395,525",
        "Position":  "Medical Representative",
        "Product3Incentive":  "94,926 ",
        "IncentiveAmountTCFA":  "79,105",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Manapbayeva Assel",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "94,926 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "44",
        "Quarter":  "Q1",
        "Product4Incentive":  "44,299 ",
        "IncentiveAmountSalesResult":  "442,988",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "199,345 ",
        "TotalIncentiveAmount":  "522,093",
        "Position":  "Pharm Representative",
        "Product3Incentive":  "66,448 ",
        "IncentiveAmountTCFA":  "79,105",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Maximenko Alexandr",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "132,896 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "45",
        "Quarter":  "Q1",
        "Product4Incentive":  "12,973 ",
        "IncentiveAmountSalesResult":  "259,464",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "129,732 ",
        "TotalIncentiveAmount":  "338,569",
        "Position":  "Medical Representative",
        "Product3Incentive":  "25,946 ",
        "IncentiveAmountTCFA":  "79,105",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Meirbek Ainur",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "90,813 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "46",
        "Quarter":  "Q1",
        "Product4Incentive":  "12,973 ",
        "IncentiveAmountSalesResult":  "259,464",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "129,732 ",
        "TotalIncentiveAmount":  "299,017",
        "Position":  "Medical Representative",
        "Product3Incentive":  "25,946 ",
        "IncentiveAmountTCFA":  "39,553",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Nakipbekova Gulzhan",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "90,813 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "47",
        "Quarter":  "Q1",
        "Product4Incentive":  "32,433 ",
        "IncentiveAmountSalesResult":  "648,661",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "291,897 ",
        "TotalIncentiveAmount":  "688,214",
        "Position":  "Medical Representative",
        "Product3Incentive":  "162,165 ",
        "IncentiveAmountTCFA":  "39,553",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Novokhatnyaya Anastasiya",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "162,165 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "48",
        "Quarter":  "Q1",
        "Product4Incentive":  "39,553 ",
        "IncentiveAmountSalesResult":  "791,050",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "395,525 ",
        "TotalIncentiveAmount":  "830,603",
        "Position":  "Medical Representative",
        "Product3Incentive":  "79,105 ",
        "IncentiveAmountTCFA":  "39,553",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Omarova Aizhan",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "276,868 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "49",
        "Quarter":  "Q1",
        "Product4Incentive":  "132,896 ",
        "IncentiveAmountSalesResult":  "664,482",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "199,345 ",
        "TotalIncentiveAmount":  "743,587",
        "Position":  "Medical Representative",
        "Product3Incentive":  "166,121 ",
        "IncentiveAmountTCFA":  "79,105",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Ospanova Anar",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "166,121 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "50",
        "Quarter":  "Q1",
        "Product4Incentive":  "74,359 ",
        "IncentiveAmountSalesResult":  "743,587",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "334,614 ",
        "TotalIncentiveAmount":  "783,140",
        "Position":  "Pharm Representative",
        "Product3Incentive":  "111,538 ",
        "IncentiveAmountTCFA":  "39,553",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Ossipova Anna",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "223,076 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "51",
        "Quarter":  "Q1",
        "Product4Incentive":  "25,314 ",
        "IncentiveAmountSalesResult":  "506,272",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "253,136 ",
        "TotalIncentiveAmount":  "545,825",
        "Position":  "Medical Representative",
        "Product3Incentive":  "50,627 ",
        "IncentiveAmountTCFA":  "39,553",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Pavlutskikh Yelena",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "177,195 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "52",
        "Quarter":  "Q1",
        "Product4Incentive":  "23,732 ",
        "IncentiveAmountSalesResult":  "474,630",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "237,315 ",
        "TotalIncentiveAmount":  "553,735",
        "Position":  "Medical Representative",
        "Product3Incentive":  "47,463 ",
        "IncentiveAmountTCFA":  "79,105",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Rakhimzhanova Gulnar",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "166,121 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "53",
        "Quarter":  "Q1",
        "Product4Incentive":  "50,627 ",
        "IncentiveAmountSalesResult":  "506,272",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "227,822 ",
        "TotalIncentiveAmount":  "585,377",
        "Position":  "Pharm Representative",
        "Product3Incentive":  "75,941 ",
        "IncentiveAmountTCFA":  "79,105",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Sadvakassova Zhanat",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "151,882 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "54",
        "Quarter":  "Q1",
        "Product4Incentive":  "0 ",
        "IncentiveAmountSalesResult":  "0",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "0.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "0 ",
        "TotalIncentiveAmount":  "0",
        "Position":  "Pharm Representative",
        "Product3Incentive":  "0 ",
        "IncentiveAmountTCFA":  "0",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Sagimbayeva Lyazat",
        "TargetIncentiveTCFA":  "0",
        "Product2Incentive":  "0 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "55",
        "Quarter":  "Q1",
        "Product4Incentive":  "44,299 ",
        "IncentiveAmountSalesResult":  "221,494",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "66,448 ",
        "TotalIncentiveAmount":  "261,047",
        "Position":  "Medical Representative",
        "Product3Incentive":  "55,374 ",
        "IncentiveAmountTCFA":  "39,553",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Sakalbayeva Aliya",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "55,374 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "56",
        "Quarter":  "Q1",
        "Product4Incentive":  "0 ",
        "IncentiveAmountSalesResult":  "0",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "0.00",
        "TargetIncentiveBase":  "263,683.33",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "0 ",
        "TotalIncentiveAmount":  "0",
        "Position":  "Pharm Representative",
        "Product3Incentive":  "0 ",
        "IncentiveAmountTCFA":  "0",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Sarbassova Dina (Shymkent)",
        "TargetIncentiveTCFA":  "0",
        "Product2Incentive":  "0 ",
        "ReimbursableMonths":  "67%"
    },
    {
        "Id":  "57",
        "Quarter":  "Q1",
        "Product4Incentive":  "22,149 ",
        "IncentiveAmountSalesResult":  "221,494",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "99,672 ",
        "TotalIncentiveAmount":  "300,599",
        "Position":  "Pharm Representative",
        "Product3Incentive":  "33,224 ",
        "IncentiveAmountTCFA":  "79,105",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Sariyeva Ainur",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "66,448 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "58",
        "Quarter":  "Q1",
        "Product4Incentive":  "23,732 ",
        "IncentiveAmountSalesResult":  "474,630",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "237,315 ",
        "TotalIncentiveAmount":  "553,735",
        "Position":  "Medical Representative",
        "Product3Incentive":  "47,463 ",
        "IncentiveAmountTCFA":  "79,105",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Sarsenbayeva Saniya",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "166,121 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "59",
        "Quarter":  "Q1",
        "Product4Incentive":  "16,876 ",
        "IncentiveAmountSalesResult":  "168,757",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "105,473.33",
        "TargetIncentiveBase":  "131,841.67",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "75,941 ",
        "TotalIncentiveAmount":  "168,757",
        "Position":  "Pharm Representative",
        "Product3Incentive":  "25,314 ",
        "IncentiveAmountTCFA":  "0",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Simachkova Yelena",
        "TargetIncentiveTCFA":  "26,368",
        "Product2Incentive":  "50,627 ",
        "ReimbursableMonths":  "33%"
    },
    {
        "Id":  "60",
        "Quarter":  "Q1",
        "Product4Incentive":  "94,926 ",
        "IncentiveAmountSalesResult":  "316,420",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "31,642 ",
        "TotalIncentiveAmount":  "395,525",
        "Position":  "Medical Representative",
        "Product3Incentive":  "94,926 ",
        "IncentiveAmountTCFA":  "79,105",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Soni Laura",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "94,926 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "61",
        "Quarter":  "Q1",
        "Product4Incentive":  "71,148 ",
        "IncentiveAmountSalesResult":  "1,422,960",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "580,800.00",
        "TargetIncentiveBase":  "726,000.00",
        "TargetIncentiveForQuarter":  "726,000.00 ",
        "Product1Incentive":  "711,480 ",
        "TotalIncentiveAmount":  "1,568,160",
        "Position":  "Regional Manager",
        "Product3Incentive":  "284,592 ",
        "IncentiveAmountTCFA":  "72,600",
        "TargetIncentiveCoaching":  "72,600",
        "IncentiveAmountCoaching":  "72,600",
        "Name":  "Suttubayeva Gulnar",
        "TargetIncentiveTCFA":  "72,600",
        "Product2Incentive":  "355,740 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "62",
        "Quarter":  "Q1",
        "Product4Incentive":  "158,210 ",
        "IncentiveAmountSalesResult":  "791,050",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "237,315 ",
        "TotalIncentiveAmount":  "870,155",
        "Position":  "Medical Representative",
        "Product3Incentive":  "197,763 ",
        "IncentiveAmountTCFA":  "79,105",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Tasbulatova Saule",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "197,763 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "63",
        "Quarter":  "Q1",
        "Product4Incentive":  "12,973 ",
        "IncentiveAmountSalesResult":  "259,464",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "129,732 ",
        "TotalIncentiveAmount":  "299,017",
        "Position":  "Medical Representative",
        "Product3Incentive":  "25,946 ",
        "IncentiveAmountTCFA":  "39,553",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Temirbayeva Akzhunis",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "90,813 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "64",
        "Quarter":  "Q1",
        "Product4Incentive":  "12,973 ",
        "IncentiveAmountSalesResult":  "259,464",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "129,732 ",
        "TotalIncentiveAmount":  "338,569",
        "Position":  "Medical Representative",
        "Product3Incentive":  "25,946 ",
        "IncentiveAmountTCFA":  "79,105",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Tilessova Altynay",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "90,813 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "65",
        "Quarter":  "Q1",
        "Product4Incentive":  "132,896 ",
        "IncentiveAmountSalesResult":  "664,482",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "199,345 ",
        "TotalIncentiveAmount":  "704,035",
        "Position":  "Medical Representative",
        "Product3Incentive":  "166,121 ",
        "IncentiveAmountTCFA":  "39,553",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Tipalov Sergey",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "166,121 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "66",
        "Quarter":  "Q1",
        "Product4Incentive":  "11,075 ",
        "IncentiveAmountSalesResult":  "221,494",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "99,672 ",
        "TotalIncentiveAmount":  "300,599",
        "Position":  "Medical Representative",
        "Product3Incentive":  "55,374 ",
        "IncentiveAmountTCFA":  "79,105",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Ungarbayeva Zhanna",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "55,374 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "67",
        "Quarter":  "Q1",
        "Product4Incentive":  "15,821 ",
        "IncentiveAmountSalesResult":  "316,420",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "158,210 ",
        "TotalIncentiveAmount":  "395,525",
        "Position":  "Medical Representative",
        "Product3Incentive":  "31,642 ",
        "IncentiveAmountTCFA":  "79,105",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Yerkin Nadiyam",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "110,747 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "68",
        "Quarter":  "Q1",
        "Product4Incentive":  "15,821 ",
        "IncentiveAmountSalesResult":  "316,420",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "158,210 ",
        "TotalIncentiveAmount":  "395,525",
        "Position":  "Medical Representative",
        "Product3Incentive":  "31,642 ",
        "IncentiveAmountTCFA":  "79,105",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Yesbolova Gulnur",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "110,747 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "69",
        "Quarter":  "Q1",
        "Product4Incentive":  "55,176 ",
        "IncentiveAmountSalesResult":  "1,103,520",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "580,800.00",
        "TargetIncentiveBase":  "726,000.00",
        "TargetIncentiveForQuarter":  "726,000.00 ",
        "Product1Incentive":  "551,760 ",
        "TotalIncentiveAmount":  "1,248,720",
        "Position":  "Regional Manager",
        "Product3Incentive":  "220,704 ",
        "IncentiveAmountTCFA":  "72,600",
        "TargetIncentiveCoaching":  "72,600",
        "IncentiveAmountCoaching":  "72,600",
        "Name":  "Yevseyenko Larissa",
        "TargetIncentiveTCFA":  "72,600",
        "Product2Incentive":  "275,880 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "70",
        "Quarter":  "Q1",
        "Product4Incentive":  "94,926 ",
        "IncentiveAmountSalesResult":  "316,420",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "31,642 ",
        "TotalIncentiveAmount":  "395,525",
        "Position":  "Medical Representative",
        "Product3Incentive":  "94,926 ",
        "IncentiveAmountTCFA":  "79,105",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Yu Vitaliya",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "94,926 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "71",
        "Quarter":  "Q1",
        "Product4Incentive":  "22,149 ",
        "IncentiveAmountSalesResult":  "442,988",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "221,494 ",
        "TotalIncentiveAmount":  "522,093",
        "Position":  "Medical Representative",
        "Product3Incentive":  "44,299 ",
        "IncentiveAmountTCFA":  "79,105",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Zhanabekova Kamshat",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "155,046 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "72",
        "Quarter":  "Q1",
        "Product4Incentive":  "32,433 ",
        "IncentiveAmountSalesResult":  "648,661",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "291,897 ",
        "TotalIncentiveAmount":  "727,766",
        "Position":  "Medical Representative",
        "Product3Incentive":  "162,165 ",
        "IncentiveAmountTCFA":  "79,105",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Zhazylbekova Aitolkyn",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "162,165 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "73",
        "Quarter":  "Q1",
        "Product4Incentive":  "24,684 ",
        "IncentiveAmountSalesResult":  "493,680",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "580,800.00",
        "TargetIncentiveBase":  "726,000.00",
        "TargetIncentiveForQuarter":  "726,000.00 ",
        "Product1Incentive":  "246,840 ",
        "TotalIncentiveAmount":  "638,880",
        "Position":  "Regional Manager",
        "Product3Incentive":  "98,736 ",
        "IncentiveAmountTCFA":  "72,600",
        "TargetIncentiveCoaching":  "72,600",
        "IncentiveAmountCoaching":  "72,600",
        "Name":  "Zhmailova Yelena",
        "TargetIncentiveTCFA":  "72,600",
        "Product2Incentive":  "123,420 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "74",
        "Quarter":  "Q1",
        "Product4Incentive":  "158,210 ",
        "IncentiveAmountSalesResult":  "791,050",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "237,315 ",
        "TotalIncentiveAmount":  "870,155",
        "Position":  "Medical Representative",
        "Product3Incentive":  "197,763 ",
        "IncentiveAmountTCFA":  "79,105",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Kaderov Nursultan",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "197,763 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "75",
        "Quarter":  "Q1",
        "Product4Incentive":  "132,896 ",
        "IncentiveAmountSalesResult":  "664,482",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "199,345 ",
        "TotalIncentiveAmount":  "743,587",
        "Position":  "Medical Representative",
        "Product3Incentive":  "166,121 ",
        "IncentiveAmountTCFA":  "79,105",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Ospanova Zhumagul",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "166,121 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "76",
        "Quarter":  "Q1",
        "Product4Incentive":  "0 ",
        "IncentiveAmountSalesResult":  "0",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "0.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "0 ",
        "TotalIncentiveAmount":  "0",
        "Position":  "Medical Representative",
        "Product3Incentive":  "0 ",
        "IncentiveAmountTCFA":  "0",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Zhanuzakova Gulbakyt",
        "TargetIncentiveTCFA":  "0",
        "Product2Incentive":  "0 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "77",
        "Quarter":  "Q1",
        "Product4Incentive":  "24,684 ",
        "IncentiveAmountSalesResult":  "493,680",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "580,800.00",
        "TargetIncentiveBase":  "726,000.00",
        "TargetIncentiveForQuarter":  "726,000.00 ",
        "Product1Incentive":  "246,840 ",
        "TotalIncentiveAmount":  "566,280",
        "Position":  "Regional Manager",
        "Product3Incentive":  "98,736 ",
        "IncentiveAmountTCFA":  "72,600",
        "TargetIncentiveCoaching":  "72,600",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Nurikhanova Alissa",
        "TargetIncentiveTCFA":  "72,600",
        "Product2Incentive":  "123,420 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "78",
        "Quarter":  "Q1",
        "Product4Incentive":  "53,791 ",
        "IncentiveAmountSalesResult":  "537,914",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "316,420.00",
        "TargetIncentiveBase":  "395,525.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "242,061 ",
        "TotalIncentiveAmount":  "617,019",
        "Position":  "Medical Representative",
        "Product3Incentive":  "80,687 ",
        "IncentiveAmountTCFA":  "79,105",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Konurub Roza",
        "TargetIncentiveTCFA":  "79,105",
        "Product2Incentive":  "161,374 ",
        "ReimbursableMonths":  "100%"
    },
    {
        "Id":  "79",
        "Quarter":  "Q1",
        "Product4Incentive":  "0 ",
        "IncentiveAmountSalesResult":  "0",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "0.00",
        "TargetIncentiveBase":  "0.00",
        "TargetIncentiveForQuarter":  "726,000.00 ",
        "Product1Incentive":  "0 ",
        "TotalIncentiveAmount":  "0",
        "Position":  "Regional Manager",
        "Product3Incentive":  "0 ",
        "IncentiveAmountTCFA":  "0",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Tulemyrzayeva Madina",
        "TargetIncentiveTCFA":  "0",
        "Product2Incentive":  "0 ",
        "ReimbursableMonths":  "0%"
    },
    {
        "Id":  "80",
        "Quarter":  "Q1",
        "Product4Incentive":  "25,841 ",
        "IncentiveAmountSalesResult":  "258,410",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "105,473.33",
        "TargetIncentiveBase":  "131,841.67",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "116,284 ",
        "TotalIncentiveAmount":  "258,410",
        "Position":  "Pharm Representative",
        "Product3Incentive":  "38,761 ",
        "IncentiveAmountTCFA":  "0",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Kusmanova Shynar",
        "TargetIncentiveTCFA":  "26,368",
        "Product2Incentive":  "77,523 ",
        "ReimbursableMonths":  "33%"
    },
    {
        "Id":  "81",
        "Quarter":  "Q1",
        "Product4Incentive":  "105,473 ",
        "IncentiveAmountSalesResult":  "527,367",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "210,946.67",
        "TargetIncentiveBase":  "263,683.33",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "158,210 ",
        "TotalIncentiveAmount":  "527,367",
        "Position":  "Medical Representative",
        "Product3Incentive":  "131,842 ",
        "IncentiveAmountTCFA":  "0",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Salikhova Akbota",
        "TargetIncentiveTCFA":  "52,737",
        "Product2Incentive":  "131,842 ",
        "ReimbursableMonths":  "67%"
    },
    {
        "Id":  "82",
        "Quarter":  "Q1",
        "Product4Incentive":  "0 ",
        "IncentiveAmountSalesResult":  "0",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "0.00",
        "TargetIncentiveBase":  "131,841.67",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "0 ",
        "TotalIncentiveAmount":  "0",
        "Position":  "Medical Representative",
        "Product3Incentive":  "0 ",
        "IncentiveAmountTCFA":  "0",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Turganbayeva Zhazira",
        "TargetIncentiveTCFA":  "0",
        "Product2Incentive":  "0 ",
        "ReimbursableMonths":  "33%"
    },
    {
        "Id":  "83",
        "Quarter":  "Q1",
        "Product4Incentive":  "10,547 ",
        "IncentiveAmountSalesResult":  "210,947",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "105,473.33",
        "TargetIncentiveBase":  "131,841.67",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "94,926 ",
        "TotalIncentiveAmount":  "224,131",
        "Position":  "Medical Representative",
        "Product3Incentive":  "52,737 ",
        "IncentiveAmountTCFA":  "13,184",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Makenova Yuliya",
        "TargetIncentiveTCFA":  "26,368",
        "Product2Incentive":  "52,737 ",
        "ReimbursableMonths":  "33%"
    },
    {
        "Id":  "84",
        "Quarter":  "Q1",
        "Product4Incentive":  "30,376 ",
        "IncentiveAmountSalesResult":  "101,254",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "105,473.33",
        "TargetIncentiveBase":  "131,841.67",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "10,125 ",
        "TotalIncentiveAmount":  "101,254",
        "Position":  "Medical Representative",
        "Product3Incentive":  "30,376 ",
        "IncentiveAmountTCFA":  "0",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Sarbassova Dina (Astana)",
        "TargetIncentiveTCFA":  "26,368",
        "Product2Incentive":  "30,376 ",
        "ReimbursableMonths":  "33%"
    },
    {
        "Id":  "85",
        "Quarter":  "Q1",
        "Product4Incentive":  "7,383 ",
        "IncentiveAmountSalesResult":  "147,663",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "210,946.67",
        "TargetIncentiveBase":  "263,683.33",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "73,831 ",
        "TotalIncentiveAmount":  "174,031",
        "Position":  "Medical Representative",
        "Product3Incentive":  "14,766 ",
        "IncentiveAmountTCFA":  "26,368",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Zhakenova Botagoz (????????? ??????????? ?.)",
        "TargetIncentiveTCFA":  "52,737",
        "Product2Incentive":  "51,682 ",
        "ReimbursableMonths":  "67%"
    },
    {
        "Id":  "86",
        "Quarter":  "Q1",
        "Product4Incentive":  "0 ",
        "IncentiveAmountSalesResult":  "0",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "0.00",
        "TargetIncentiveBase":  "0.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "0 ",
        "TotalIncentiveAmount":  "0",
        "Position":  "Medical Representative",
        "Product3Incentive":  "0 ",
        "IncentiveAmountTCFA":  "0",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Dikambayev Zhiger",
        "TargetIncentiveTCFA":  "0",
        "Product2Incentive":  "0 ",
        "ReimbursableMonths":  "0%"
    },
    {
        "Id":  "87",
        "Quarter":  "Q1",
        "Product4Incentive":  "79,105 ",
        "IncentiveAmountSalesResult":  "395,525",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "158,210.00",
        "TargetIncentiveBase":  "197,762.50",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "118,658 ",
        "TotalIncentiveAmount":  "435,078",
        "Position":  "Medical Representative",
        "Product3Incentive":  "98,881 ",
        "IncentiveAmountTCFA":  "39,553",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Dubova Yevgeniya",
        "TargetIncentiveTCFA":  "39,553",
        "Product2Incentive":  "98,881 ",
        "ReimbursableMonths":  "50%"
    },
    {
        "Id":  "88",
        "Quarter":  "Q1",
        "Product4Incentive":  "0 ",
        "IncentiveAmountSalesResult":  "0",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "0.00",
        "TargetIncentiveBase":  "0.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "0 ",
        "TotalIncentiveAmount":  "0",
        "Position":  "Medical Representative",
        "Product3Incentive":  "0 ",
        "IncentiveAmountTCFA":  "0",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Kalacheva Larissa",
        "TargetIncentiveTCFA":  "0",
        "Product2Incentive":  "0 ",
        "ReimbursableMonths":  "0%"
    },
    {
        "Id":  "89",
        "Quarter":  "Q1",
        "Product4Incentive":  "0 ",
        "IncentiveAmountSalesResult":  "0",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "0.00",
        "TargetIncentiveBase":  "0.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "0 ",
        "TotalIncentiveAmount":  "0",
        "Position":  "Medical Representative",
        "Product3Incentive":  "0 ",
        "IncentiveAmountTCFA":  "0",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Kalen Temirlan",
        "TargetIncentiveTCFA":  "0",
        "Product2Incentive":  "0 ",
        "ReimbursableMonths":  "0%"
    },
    {
        "Id":  "90",
        "Quarter":  "Q1",
        "Product4Incentive":  "15,821 ",
        "IncentiveAmountSalesResult":  "316,420",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "210,946.67",
        "TargetIncentiveBase":  "263,683.33",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "158,210 ",
        "TotalIncentiveAmount":  "342,788",
        "Position":  "Medical Representative",
        "Product3Incentive":  "31,642 ",
        "IncentiveAmountTCFA":  "26,368",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Kassanova Elmira",
        "TargetIncentiveTCFA":  "52,737",
        "Product2Incentive":  "110,747 ",
        "ReimbursableMonths":  "67%"
    },
    {
        "Id":  "91",
        "Quarter":  "Q1",
        "Product4Incentive":  "0 ",
        "IncentiveAmountSalesResult":  "0",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "0.00",
        "TargetIncentiveBase":  "0.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "0 ",
        "TotalIncentiveAmount":  "0",
        "Position":  "Pharm Representative",
        "Product3Incentive":  "0 ",
        "IncentiveAmountTCFA":  "0",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Nassyrov Farukh",
        "TargetIncentiveTCFA":  "0",
        "Product2Incentive":  "0 ",
        "ReimbursableMonths":  "0%"
    },
    {
        "Id":  "92",
        "Quarter":  "Q1",
        "Product4Incentive":  "0 ",
        "IncentiveAmountSalesResult":  "0",
        "PromoLine":  null,
        "TargetIncentiveSalesResult":  "0.00",
        "TargetIncentiveBase":  "0.00",
        "TargetIncentiveForQuarter":  "395,525.00 ",
        "Product1Incentive":  "0 ",
        "TotalIncentiveAmount":  "0",
        "Position":  "Medical Representative",
        "Product3Incentive":  "0 ",
        "IncentiveAmountTCFA":  "0",
        "TargetIncentiveCoaching":  "0",
        "IncentiveAmountCoaching":  "0",
        "Name":  "Volkova Svetlana",
        "TargetIncentiveTCFA":  "0",
        "Product2Incentive":  "0 ",
        "ReimbursableMonths":  "0%"
    }
];
